### ISSUE TITLE
Keybinding conflict for Git and Outline views

### ISSUE THREAD

**Issue by spoenemann** [theia-ide/theia#1060]
With #1028 I introduced new keybindings to toggle all views that are put into side panels. The keybindings for the Git and Outline views do not work. I see the following in the log:

```
@theia/example-browser: [2018-01-16T12:34:47.222Z]  WARN:
@theia/example-browser:     Collided keybinding is ignored;  [ '{"commandId":"monaco.editor.action.quickOutline","keyCode":{"keystroke":"KeyO+M2+M4","key":{"code":"KeyO","keyCode":79},"meta":false,"shift":true,"alt":false,"ctrl":true},"accelerator":["Accel Shift O"]}',
@theia/example-browser:       ' collided with ',
@theia/example-browser:       '{"commandId":"outlineView:toggle","keyCode":{"keystroke":"KeyO+M2+M4","key":{"code":"KeyO","keyCode":79},"meta":false,"shift":true,"alt":false,"ctrl":true}}' ]
@theia/example-browser: [2018-01-16T12:34:47.229Z]  WARN:
@theia/example-browser:     Collided keybinding is ignored;  [ '{"commandId":"gitView:toggle","keyCode":{"keystroke":"KeyG+M2+M4","key":{"code":"KeyG","keyCode":71},"meta":false,"shift":true,"alt":false,"ctrl":true}}',
@theia/example-browser:       ' collided with ',
@theia/example-browser:       '{"commandId":"monaco.editor.action.previousMatchFindAction","keyCode":{"keystroke":"KeyG+M2+M4","key":{"code":"KeyG","keyCode":71},"meta":false,"shift":true,"alt":false,"ctrl":true},"accelerator":["Accel Shift G"]}' ]
```

The binding for Git is Ctrl + Shift + G, the same as in VS Code. It's strange that it works there, but here there are conflicts with the Monaco editor.

**Comment by svenefftinge** [comment]
We need to use a KeybindingContext (editorActive) to guard all the editor actions.

**Comment by spoenemann** [comment]
With #1065 the keybinding for Git has been changed to Cmd + Shift + G. Is that intended?

**Comment by svenefftinge** [comment]
@hexa00 ^^^ ?

**Comment by hexa00** [comment]
The outline view also is problematic.. fixing that one too..

**Comment by spoenemann** [comment]
Thanks! However the keybindings for Git and Outline views still don't work on Mac OS, although I don't see the collision warning anymore in the log.

**Comment by hexa00** [comment]
@spoenemann really? 
I think these are they only ctrl based keybindings ? 

Could you try to find another ctrl based one ? see if ctrl is not working in general?

**Comment by spoenemann** [comment]
I'm not aware of any.

**Comment by hexa00** [comment]
I would check the command palette... I don't have a mac... so I can't debug the issue :(

**Comment by kittaakos** [comment]
Currently, it is bound to `ctrl` instead of `cmd` on Mac. Apparently, `ctrl` does not work on Mac. If I change it back to `cmd` (which should be `ctrl` on Windows and Linux), it works.

```diff
diff --git a/packages/git/src/browser/git-frontend-contribution.ts b/packages/git/src/browser/git-frontend-contribution.ts
index e0963e66..5518e1be 100644
--- a/packages/git/src/browser/git-frontend-contribution.ts
+++ b/packages/git/src/browser/git-frontend-contribution.ts
@@ -39,7 +39,7 @@ export class GitFrontendContribution extends AbstractViewContribution<GitWidget>
                 rank: 200
             },
             toggleCommandId: 'gitView:toggle',
-            toggleKeybinding: 'ctrl+shift+g'
+            toggleKeybinding: 'ctrlcmd+shift+g'
         });
     }
 
diff --git a/packages/outline-view/src/browser/outline-view-contribution.ts b/packages/outline-view/src/browser/outline-view-contribution.ts
index a04a12fa..4e750df8 100644
--- a/packages/outline-view/src/browser/outline-view-contribution.ts
+++ b/packages/outline-view/src/browser/outline-view-contribution.ts
@@ -23,7 +23,7 @@ export class OutlineViewContribution extends AbstractViewContribution<OutlineVie
                 rank: 500
             },
             toggleCommandId: 'outlineView:toggle',
-            toggleKeybinding: 'ctrl+shift+o'
+            toggleKeybinding: 'ctrlcmd+shift+o'
         });
     }
 }
```

> With #1065 the keybinding for Git has been changed to Cmd + Shift + G. Is that intended?

@spoenemann, Did you mean [this](https://github.com/theia-ide/theia/pull/1065/files#diff-d86a105da42850a54d9cc2b0ad3af23aR37)? That is a `cmd+shift+g` on Mac, so that did not change the semantics.

**Comment by svenefftinge** [comment]
@kittaakos it makes sense. Please change it to `ctrlcmd`.

**Comment by kittaakos** [comment]
OK, I will take care of this task.

**Comment by hexa00** [comment]
But why is `ctrl` not working on mac ?

**Comment by kittaakos** [comment]
Good question... I do not know yet. But for instance `` Cmd+` `` does not work either. Only the meta `Cmd` propagates to our keybinding code but the backtick never arrives.

**Comment by hexa00** [comment]
>The binding for Git is Ctrl + Shift + G, the same as in VS Code. It's strange that it works there, but here there are conflicts with the Monaco editor.

Why change it to CmdCtrl+G on mac ?

We should fix the keybindings in general for mac instead?

**Comment by kittaakos** [comment]
Alt+shit+w, close all editor does not work either.

**Comment by kittaakos** [comment]
This issue seems to be browser specific on OS X. At least I am having troubles capturing some of the key events in Chrome. Works in Safari. I am using US English layout.

**Comment by kittaakos** [comment]
> This issue seems to be browser specific on OS X.

Try out: https://jsfiddle.net/kittaakos/3q316zn6/

**Comment by kittaakos** [comment]
> Alt+shit+w, close all editor does not work either.

This seems to work on Chrome, still not handled by Theia. See the events with different browsers:
```
Safari: 8222 + KeyW + Shift + Alt
Chrom: 8222 + KeyW + Shift + Alt
FF: 0 + KeyW + Shift + Alt
```

**Comment by kittaakos** [comment]
Regarding the `Close all` issue, I think either `KeySequence.parse` or the `KeySequence.compare` is too strict:

When pressing either <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>W</kbd> or <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>W</kbd> I get the the following `keyCode.keystroke`: `"KeyW+M2+M3"` and binding for the the `Close All` command (`core.close.all.tabs`) expects the following `keyCode.keystroke`: `"KeyW+M3+M2"`.

**Comment by kittaakos** [comment]
> But why is ctrl not working on mac ?

It is due to the [above-mentioned](https://github.com/theia-ide/theia/issues/1060#issuecomment-366915412) parser behavior.

**Comment by kittaakos** [comment]
There is another bug with the parser, the following event:
```
KeyboardEvent {isTrusted: true, key: "`", code: "Backquote", location: 0, ctrlKey: true, …}
	altKey: false
	bubbles: true
	cancelBubble: false
	cancelable: true
	charCode: 0
	code: "Backquote"
	composed: true
	ctrlKey: true
	currentTarget: document
	defaultPrevented: false
	detail: 0
	eventPhase: 1
	isComposing: false
	isTrusted: true
	key: "`"
	keyCode: 192
	location: 0
	metaKey: false
	path: (9) [div#files.p-Widget.theia-Tree.theia-FileTree.theia-Files.p-DockPanel-widget, div#theia-left-side-panel.p-Widget.p-DockPanel.p-BoxPanel-child, div#theia-left-content-panel.p-Widget.p-Panel.p-BoxPanel.p-SplitPanel-child, div#theia-left-right-split-panel.p-Widget.p-Panel.p-SplitPanel, div#theia-app-shell.p-Widget.theia-ApplicationShell, body.vs, html.gr__localhost, document, Window]
	repeat: false
	returnValue: true
	shiftKey: false
	sourceCapabilities: InputDeviceCapabilities {firesTouchEvents: false}
	srcElement: div#files.p-Widget.theia-Tree.theia-FileTree.theia-Files.p-DockPanel-widgettarget: div#files.p-Widget.theia-Tree.theia-FileTree.theia-Files.p-DockPanel-widget
	timeStamp: 836392.200000002
	type: "keydown"
	view: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, frames: Window, …}which: 192__proto__: KeyboardEvent
```
is parsed as `Backquote+M1+M4` which is incorrect. I have used <kbd>control</kbd>+<kbd>`</kbd> on OS X.
