### ISSUE TITLE
[git] project shows on the status bar even after deleting the project from the workspace

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#3842]
To reproduce:
  1- clone a project into your workspace
  2- At the bottom in the status bar, you can select the project and it shows in the quick-open view: OK
  3- From your workspace, select the project and delete it.
Error : ==> The branch still shows on the status bar at the bottom left
Step 2: ==> Select the project. it opens the quick-open view in it, then select it , it generates the following error on the server console:

root ERROR Request status failed with error: Unable to find path to repository on disk. Error: Unable to find path to repository on disk.
    at /home/lmcbout/theia/theia/node_modules/dugite/build/lib/git-process.js:87:39
    at exithandler (child_process.js:283:5)
    at ChildProcess.errorhandler (child_process.js:295:5)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by westbury** [comment]
This issue is fixed by pull-request https://github.com/theia-ide/theia/pull/3831

**Comment by vince-fugnitto** [comment]
@lmcbout can you verify if the pr #3831 fixes the issue?

**Comment by lmcbout** [comment]
@vince-fugnitto It solves 95% of the issue.
We can reproduce this issue because it takes too much time to remove the deleted branch from the status bar.  The end-user can still select the project after delete on the status bar, then it shows again in the quick-open menu and just select it  ==> problem still present. If the end-user waits until the status bar is updated (~5 sec), then the problem does not occur.

**Comment by vince-fugnitto** [comment]
@lmcbout 
I'm not sure if its a common use case, and the PR most likely addresses it adequately, perhaps we can look to improving the performance in the future?

**Comment by lmcbout** [comment]
Close enough, it is a matter of performance. May be the order of events could prevent the remaining issue.
